### PR TITLE
switch to engine 5.4.0-dev-r1

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
Includes lot of changes in regards to map loading, sending and saving
Engine commit: https://github.com/minetest/minetest/commit/f1d72d212a0661588be27003069abf4bd8092e55
Docker image: https://github.com/pandorabox-io/minetest_docker/commit/33d06f192b8a1a0d9fc6a4737d7511738b9a0b99

Important changes:
* https://github.com/minetest/minetest/pull/10670
* https://github.com/minetest/minetest/pull/10637
* https://github.com/minetest/minetest/pull/10616

It should also contain some anticheat stuff (should make this obsolete: https://github.com/pandorabox-io/pandorabox_custom/blob/master/anticheat/inv_move.lua)

### CODE REVIEW

**Comment by OgelGames** [comment]
There are at least a couple of issues that need to be fixed before switching to 5.4.0-dev, one is https://github.com/minetest-mods/inspector/issues/15, and the other I think is some textures not looking right (I'll have to check again).

I have been doing all my testing in 5.4.0-dev though, so I don't think there's much else...

**Comment by BuckarooBanzay** [comment]
> There are at least a couple of issues that need to be fixed before switching to 5.4.0-dev, one is [minetest-mods/inspector#15](https://github.com/minetest-mods/inspector/issues/15), and the other I think is some textures not looking right (I'll have to check again).
> 
> I have been doing all my testing in 5.4.0-dev though, so I don't think there's much else...

This is live on the test-server, not sure if the mods are up-to-date though, checking that later...

**Comment by BuckarooBanzay** [comment]
closing this, i think i'll make a new version with the changes from https://github.com/minetest/minetest/pull/10709 and without _my_ async ~~crap~~ stuff

**Comment by lhofhansl** [comment]
I'd be a little careful about minetest/minetest#10709. While I think it will work correctly I am not happy with it yet, and not much testing has happened with it.
minetest/minetest#10715 get you part way there since map compression at Zlib level 3 is about 3x faster than default level 6.

I'm curious to see your async approach. Do you make the entire save async or just the compression?

**Comment by BuckarooBanzay** [comment]
> I'd be a little careful about minetest/minetest#10709. While I think it will work correctly I am not happy with it yet, and not much testing has happened with it.

Don't worry, i'm usually testing things like that on the test-server :wink:

> I'd be a little careful about minetest/minetest#10709. While I think it will work correctly I am not happy with it yet, and not much testing has happened with it.

Oh, nice, i almost missed that feature :+1: 

> I'm curious to see your async approach. Do you make the entire save async or just the compression?

My approach was very hacky at best, the current patch for it is here: https://github.com/pandorabox-io/minetest_docker/blob/master/patches/minetest_async_pg.patch
It currently is backed into the `postgres` database classes/connection

It worked like this:
* A new thread for sending the mapblocks to the database
* A new thread for sending the player-data to the database
* `PlayerDatabasePostgreSQL::savePlayer` serializes the player-data and hands it off to the player-save thread
* `MapDatabasePostgreSQL::saveBlock` serializes the mapblocks (in a separate thread-pool) and hands that off to the mapblock-save thread

It improved performance quite a bit, there were lag-spikes every "map-save interval" seconds in the order of multiple seconds before the patch, after it this was gone.

The only downside so far (besides the miserable code-quality) is a very exotic race-condition:
If a mapblock is in the async save-queue and accessed at the same time it can happen that the stale mapblock got loaded from the database _before_ the update got executed. This can result in "forgotten" block placement and in more sever cases (with the `jumpdrive` mod for example) if whole mapblocks get rewritten in the loss of the newly written mapblock.
But that happened so far only in a handful of cases :crossed_fingers:

**Comment by lhofhansl** [comment]
I see. So in your case it the save to Postgres itself that is "slow"?
With sqlite I find the main source of delay is the Zlib compression. So my patch hands that off to another thread. Since sqlite is not threadsafe the actual saving is done on the other thread as well, but it take the server-global envlock, and so would still stall much of the other parts of the server including Lua, sending blocks to the client, etc.

Generally there are four things save does:
1. Collect the dirty block - usually fast
2. For each block serialize its parts - somewhat slow
3. For each block compress nodes and metadata - quite slow and CPU intensive
4. For each block save it to the data base - fast with sqlite

As is, all of these are done on the server thread and while taking the serverenvironment lock.

10709 does this all on a separate thread.
But ... 1), most of 2), and 4) still need the global serverenvironment lock.
Only 3) is done completely without locking.

So if 4) - the save to the DB - is what you see as slow then 10709 would not help you.

**Comment by lhofhansl** [comment]
Pushed another update. Maybe you can have a look. The DB Save is still done under lock. Unfortunately that part is database dependent. (Could add a method to the DB backend to ask whether it supports multi-threading. If so, I can just avoid taking the lock in the saver thread.)

In any case, I wonder whether you see an improvement with that latest version.

**Comment by BuckarooBanzay** [comment]
> So if 4) - the save to the DB - is what you see as slow then 10709 would not help you.

I _think_ the issue was the latency overhead in our case back then, we recently switched from a tcp-connection to a socket-based connection (https://github.com/pandorabox-io/pandorabox.io/pull/586) maybe that will improve things a bit when i remove my async patch again..

**Pull request closed without merging**
